---
title: "Tidy Tuesday - May 2, 2023"
output: html_notebook
---

```{r Libraries, Fonts, Data}
library(tidyverse)
library(showtext)
library(ggtext)
library(patchwork)

# Fonts
font_add_google("Roboto")
font_add_google("Roboto Condensed")
showtext_auto()

# Read in Data
tuesdata <- tidytuesdayR::tt_load(2023, week = 17)
```

```{r Data Exploration}
winners <- tuesdata$winners
london_marathon <- tuesdata$london_marathon

winnersNationality <- winners %>%
  left_join(london_marathon, by = "Year") %>%
  mutate(Nationality = case_when(Nationality == "United States"~"US",
                                 Nationality == "United Kingdom"~"UK",
                                 .default = Nationality)) %>%
  count(Category, Nationality, sort = TRUE) %>%
  mutate(Category = factor(Category))

winnersTimes <- winners %>% 
    left_join(london_marathon, by = "Year")
```

```{r Data Visualization}
plotNationality <- ggplot(winnersNationality, aes(x = Nationality, y = n, fill = Category)) +
  geom_col(position = position_dodge2(preserve = "single")) +
  scale_fill_manual(values = c("#0079AF", "#073763", "#C90076", "#FA8072")) +
  labs(x = "",
       y = "Number of Wins") +
  cowplot::theme_minimal_grid() +
  theme(text = element_text(family = "Roboto Condensed"),
        plot.background = element_rect(fill = "grey95",
                                       colour = "grey95"),
        panel.background = element_rect(fill = "grey95",
                                       colour = "grey95"),
        legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1))

plotTimes <- ggplot(winnersTimes, aes(x = Year, y = Time, group = Category, fill = Category, colour = Category)) +
    ggrepel::geom_text_repel(data = winnersTimes %>% filter(Year == 2010), 
                           aes(label = Category), family = "Roboto Condensed",
                           fontface = "bold", show.legend = FALSE) +
  geom_line() +
  geom_point() +
  scale_fill_manual(values = c("#0079AF", "#073763", "#C90076", "#FA8072")) +
  scale_colour_manual(values = c("#0079AF", "#073763", "#C90076", "#FA8072")) +
  cowplot::theme_minimal_grid() +
  theme(text = element_text(family = "Roboto Condensed"),
        plot.background = element_rect(fill = "grey95",
                                       colour = "grey95"),
        panel.background = element_rect(fill = "grey95",
                                       colour = "grey95"),
        legend.position = "none")

plotFinal <- plotTimes / plotNationality + plot_layout(heights = c(2, 1))
plotFinal <- plotFinal  + plot_annotation(
  title = "London Marathon Winners (1981-2022)",
  subtitle = "This graphic explores the trend in finishing time by category and number of winners by nationality and category for the London Marathon.",
  caption = "Source: @nrennie {LondonMarathon} | #TidyTuesday | Week 17"
) & theme(text = element_text(family = "Roboto Condensed"),
        plot.background = element_rect(fill = "grey95",
                                       colour = "grey95"),
        panel.background = element_rect(fill = "grey95",
                                       colour = "grey95"),
        plot.title.position = "plot",
        plot.title = element_text(family = "Roboto", face = "bold", size = 46),
        plot.subtitle = element_textbox_simple(size = 32),
        axis.text = element_text(size = 26),
        axis.title = element_text(size = 32),
        plot.caption.position = "plot",
        plot.caption = element_text(size = 28))


```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-04-25_LondonMarathon"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.8, dpi = 300,
       height = 8, width = 11, unit = "in")
```