---
title: "Tidy Tuesday - January 3, 2023"
output: html_notebook
---
```{r}
library(tidyverse)
library(sf)
library(tigris)
library(lubridate)
library(grid)
# library(geofacet)
# library(ggtext)
# library(sysfonts)
# library(cowplot)
```

```{r}
#Read in data
#tuesdata <- tidytuesdayR::tt_load(2023, week = 1)
dataSac <- readxl::read_xlsx("2023-01-03_TidyTuesdayData.xlsx", sheet = "SacRiver") %>%
  rename("ID" = "Station ID",
         "IncrementalPPT" = "PPT INC INCHES",
         "AccumulatedPPT" = "RAIN INCHES")
dataSac$DATE <- mdy(dataSac$DATE)

dataSJR <- readxl::read_xlsx("2023-01-03_TidyTuesdayData.xlsx", sheet = "SanJoaquinRiver") %>%
    rename("ID" = "Station ID",
         "IncrementalPPT" = "PPT INC INCHES",
         "AccumulatedPPT" = "RAIN INCHES")

dataTLB <- readxl::read_xlsx("2023-01-03_TidyTuesdayData.xlsx", sheet = "TulareLake") %>%
  select(-c(...6)) %>%
  rename("ID" = "Station ID",
         "IncrementalPPT" = "PPT INC INCHES",
         "AccumulatedPPT" = "RAIN INCHES")
```

```{r}
#Generate Station Map
coordSac <- st_as_sf(dataSac, coords = c("Longitude", "Latitude")) %>%
  st_set_crs(4269)

coordSJR <- st_as_sf(dataSJR, coords = c("Longitude", "Latitude")) %>%
  st_set_crs(4269)

coordTLB <- st_as_sf(dataTLB, coords = c("Longitude", "Latitude")) %>%
  st_set_crs(4269)

caMap <- counties(state = 06) %>%
  st_as_sf()

WHI <- dataSac %>% 
  filter(ID == "WHI") %>%
  ggplot() +
  geom_line(aes(x = DATE, y = AccumulatedPPT)) +
  theme(axis.text.x = element_text(size = 3, angle = 45))

SHA <- dataSac %>% 
  filter(ID == "SHA") %>%
  ggplot() +
  geom_line(aes(x = DATE, y = AccumulatedPPT))

SMF <- dataSac %>% 
  filter(ID == "SMF") %>%
  ggplot() +
  geom_line(aes(x = DATE, y = AccumulatedPPT))

FLD <- dataSac %>% 
  filter(ID == "FLD") %>%
  ggplot() +
  geom_line(aes(x = DATE, y = AccumulatedPPT))

CSU <- dataSac %>% 
  filter(ID == "CSU") %>%
  ggplot() +
  geom_line(aes(x = DATE, y = AccumulatedPPT))

CA <- ggplot() +
  geom_sf(data = caMap) +
  geom_sf(data = coordSac) +
  geom_sf(data = coordSJR) +
  geom_sf(data = coordTLB) +
  theme_void()

plotFinal <- CA + annotation_custom(ggplotGrob(WHI), ymin = 40, ymax = 42.5, xmin = -124.8, xmax = -130)
  
```

