```{r library, data, fonts}
#libraries
library(tidyverse)
library(showtext)

#data
#tuesdata <- tidytuesdayR::tt_load('2022-09-06')
inventories <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-06/inventories.csv.gz')
inventory_sets <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-06/inventory_sets.csv.gz')
sets <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-06/sets.csv.gz')


#fonts
font_add_google("Roboto")
showtext_auto()
```

```{r data analysis}
common_col_names <- intersect(names(inventory_sets), names(sets))
legoSets <- merge(inventory_sets, sets, by = common_col_names, all.x = TRUE)

common_col_names <- intersect(names(legoSets), names(inventories))
legoSets <- merge(legoSets, inventories, by = common_col_names, all.x = TRUE)

sets %>%
  group_by(year) %>%
  summarise(n = n(),
            min_parts = min(num_parts),
            mean_parts = mean(num_parts),
            max_parts = max(num_parts),
            .groups = "drop") %>%
  ggplot(aes(year, mean_parts)) +
  geom_area(alpha = 0.5, fill = "cornflowerblue") +
  geom_point(aes(size = n), color = "cornflowerblue") +
  scale_size_continuous(range = c(1,3)) +
  labs(x = "",
       y = "Average # of Parts",
       size = "# of Inventory",
       title = "Lego Sets") +
  theme(axis.text = element_text(family = "Roboto", size = 32),
        title = element_text(family = "Roboto", size = 42),
        legend.text = element_text(family = "Roboto", size = 36))

ggsave("2022-09-06_TT.png")

```
