---
title: "Tidy Tuesday - June 14, 2022"
output: html_notebook
---
```{r}
library(tidyverse)
library(lubridate)
library(geofacet)
library(ggtext)
library(sysfonts)
library(cowplot)
```


```{r}
#Read in data
tuesdata <- tidytuesdayR::tt_load("2022-06-14")


#process and clean data
drought <- tuesdata$drought %>%
  subset(select = -c(`0`, `-9`)) %>%
  mutate(DATE = gsub('d_', "", DATE),                                #Find pattern in date
         DATE = as.Date(DATE, format = '%Y%m%d'),                    #Convert Date
         state = str_replace(state,    "-", " "),                    #Remove space
         state = str_to_title(state),
         state_abb = state.abb[match(state, state.name)])

#Process and Clean -- Average by Date and State
droughtCleaned <- drought %>%
  group_by(DATE, state) %>%
  summarize(across(D0:W4, ~mean(.x)))

#process and clean data -- Mapped 
droughtWet <- drought %>%                               
  mutate(D0 = D0 - D1,
         D1 = D1 - D2,
         D2 = D2 - D3,
         D3 = D3 - D4,
         W0 = W0 - W1,
         W1 = W1 - W2,
         W2 = W2 - W3,
         W3 = W3 - W4) %>%
  filter(year(DATE) >= 2000,
         !state %in% c('Hawaii', 'Alaska')) %>%
  group_by(state_abb, DATE, state) %>%
  pivot_longer(-c(state_abb, DATE, state), names_to = 'DI', values_to = 'Perc') %>%
  mutate(Perc = ifelse(grepl('D', DI), Perc * 1, Perc * -1))

  
#Generate Grid (US - HI, AK)
gridUS = us_state_grid1 %>%
  filter(!code %in% c('HI', 'AK'))

#Generate Color Palette
colPal <- c("#FDDBC7", "#D1E5F0", "#67001F", "#053061", "#B2182B",
            "#2166AC", "#F4A582", "#92C5DE", "#D6604D", "#4393C3") 

#Plot
plotDrought <- ggplot(droughtWet) +
  geom_text(aes(as.Date('2018-10-15'), y = 65, label = state_abb), 
            size = 4, color = 'grey70', family = 'sans', fontface = 'bold') +
  geom_area(aes(x = DATE, y = Perc, fill = DI)) +
  scale_fill_manual(values = c("#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4", "#313695",
                             "#FEE090", "#FDAE61", "#F46D43", "#D73027", "#A50026"),
                    breaks = c("W0", "W1", 'W2', "W3", "W4", "D0", "D1", "D2", "D3", "D4"),                 
                    labels = c("Abnormal Wet Spell", "Moderate Wet Spell", "Severe Wet Spell", 
                               "Extreme Wet Spell", "Exceptional Wet Spell",
                               "Abnormally Dry", "Moderate Drought", "Severe Drought",
                               "Extreme Drought", "Exceptional Drought")) +
  facet_geo(~state, grid = gridUS) +
  theme_void() +
  theme(plot.background = element_rect(fill = 'white', colour = 'white'),
        plot.margin = margin(3, 0.5, 0.5, 0.5, "cm"),
        strip.text = element_blank(),
        legend.direction = 'horizontal',
        legend.position = 'bottom',
        legend.justification = 'center',
        legend.text = element_text(margin = margin(0, -1, 0, -1, "cm"), family = "sans", face = "bold",
                                   size = 10, color = "grey60"),
        legend.title = element_text(family = 'sans', face = 'bold', size = 16, 
                                    hjust = 0.5, color = 'grey60'),
        legend.key.size = unit(0.5, "cm")) +
  guides(fill = guide_legend(nrow = 1, byrow = TRUE, reverse = FALSE, title = 'Drought Conditions',
                             title.position = 'top', title.justification = 'center',
                             label.position = 'bottom',
                             keywidth = 8, vjust = -5))

plotDroughtAnn <- ggdraw(plotDrought) +
  draw_text("Drought Conditions Across the United States", x = 0.5, y = 0.95,
            fontface = "bold", size = 28, family = "sans", color = "grey60") +
  draw_text("2000-2022", x = 0.5, y = 0.9, fontface = 'bold', 
            size = 20, family = 'sans', color = 'grey60') +
  draw_text('Source: National Integrated Drought Information System', x = 0.9, y = 0.01,
            fontface = "bold", size = 8, family = "sans", color = 'grey60', vjust = -0.001)

ggsave(filename = "2022-06-14_TT.png", width = 20, height = 9, unit = "in")

#Process and Clean -- Drought by State
droughtFIPS <- tuesdata$`drought-fips`

plotDroughtFIPS <- droughtFIPS %>%
  group_by(State) %>%
  summarise(avg = mean(DSCI)) %>%
  arrange(-avg) %>%
  ggplot(aes(avg, fct_reorder(State, avg))) + 
  geom_col(width = 0.8, color = 'black', fill = 'tomato') +
  labs(y = "", x = "Average Drought", 
       title = "Severe Drought by State", subtitle = "Drought Scale = 0-200") +
  theme_cowplot() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text =  element_text(size = 8))
```
