```{r packages}
library(tidyverse)
library(wesanderson)
library(showtext)
library(lubridate)
library(patchwork)
library(geofacet)
```

```{r load data}
tuesdata <- tidytuesdayR::tt_load("2022-07-12")

#Load Fonts
font_add("Roboto", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/Roboto-Regular.ttf", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/Roboto-Bold.ttf")
font_add("Source Sans Pro", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/SourceSansPro-Regular.ttf", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/SourceSansPro-Bold.ttf")
font_add("Impact", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/Impact.ttf")

#Load Palette
pal1 <- wes_palette("Zissou1", 7, type = "continuous")
```

```{r data analysis}
minDate = min(tuesdata$flights$FLT_DATE)
maxDate = max(tuesdata$flights$FLT_DATE)

flights <- tuesdata$flights %>%
  mutate(dateGrouped = ifelse(FLT_DATE < ymd("2020-03-11"), "Pre-COVID",
                              ifelse(FLT_DATE > ymd("2021-10-17"), "Since COVID", "Mid-COVID"))) %>%
  group_by(STATE_NAME, dateGrouped) %>%
  summarise(flightTotal = sum(FLT_TOT_1), .groups = "drop") %>%
  #ungroup() %>%
  pivot_wider(names_from = dateGrouped, values_from = flightTotal) %>%
  mutate(preCOVIDPM = `Pre-COVID`/ ((interval(minDate, ymd("2020-03-11")) %/% days(1))/ 30.4375),
         sinceCOVIDPM = `Since COVID` / ((interval(ymd("2021-10-18"), maxDate) %/% days(1))/ 30.4375),
         recoveryPM = sinceCOVIDPM/ preCOVIDPM,
         group = as.factor(ifelse(recoveryPM < 0.5, "sub-50", ifelse(recoveryPM < 1, "sub-100", "plus-100"))))

flights$group = factor(flights$group, levels = c("sub-50", "sub-100", "plus-100"))

#plot data
##legend setup
lej <-
  data.frame(
    a = "group", 
    b = 1.1, 
    c = 0.76, 
    d = 0.49
    )

l <-
  ggplot(lej, aes(ymin = 0, ymax = 1, xmax = 2, xmin = 1)) +
  geom_rect(aes(ymin = 0, ymax = 1, xmax = 2, xmin = 1), fill = "#D9CAB3") +
  geom_segment(aes(y = 1, yend = 1, x = 0.5, xend = 2), 
               color = '#fcfcfc', 
               size = 2) +
  geom_rect(aes(ymin = 0, ymax = b, xmax = 2, xmin = 1.64), fill = "#FFBC42") +
  geom_rect(aes(ymin = 0, ymax = c, xmax = 1.645, xmin = 1.34), fill = "#C45E43") +
  geom_rect(aes(ymin = 0, ymax = d, xmax = 1.345, xmin = 1), fill = "#880044") +
  coord_polar(theta = "y", start = 3*pi/2) +
  xlim(0, 2) + ylim(0, 2) +
  theme_void()

l <- 
  l +
  labs(title = "Reading the Gagues") +
  annotate("text", y = 0, x = 1.166, color = "#880044", label = "<50%", 
           hjust = 1, angle = 90, size = 3) +
  annotate("text", y = 0, x = 1.5, color = "#C45E43", label = "<100%", 
           hjust = 1, angle = 90, size = 4) +
  annotate("text", y = 0, x = 1.833, color = "#FFBC42", label = "Full", 
           hjust = 1, angle = 90, size = 4) +
  annotate("text", y = 1, x = 0.5, color = "#fcfcfc", label = "Full Recovery", 
           hjust = 1, angle = 90, size = 3) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"), 
    text = element_text(family = "raleway", color = "#D9CAB3"),
  )

p <- 
  ggplot(flights, aes(fill = group, ymin = 0, ymax = recoveryPM, xmax = 2, xmin = 1)) +
  geom_rect(aes(ymin = 0, ymax = 1, xmax = 2, xmin = 1), fill = "#D9CAB3") +
  geom_rect(show.legend = FALSE) +
  geom_segment(aes(y = 1, yend = 1, x = 0.5, xend = 2), 
               color = '#fcfcfc', 
               size = 0.75) +
  coord_polar(theta = "y", start = 3*pi/2) +
  xlim(0, 2) + ylim(0, 2) +
  facet_wrap(~ STATE_NAME, labeller = labeller(state = label_wrap_gen(width = 10)), ncol = 14, nrow = 3) +
  theme_void()

p <-
  p +
  labs(title = "European Airtravel Recovery", 
       subtitle = paste("On March 8th 2020, 15 provinces in Italy were shut down due to the COVID-19 pandemic.\n", 
                        "Most of Europe would follow in the ensuing weeks, haulting airtravel.", 
                        "On October 18th 2021, \nairtravel throughout the continent resumed, but not without difficultiesreturning to former volume.\n", 
                        "The below gagues measure European's country's progress toward full recovery of pre-COVID volume.", 
                        sep = ""), 
       caption = "Data Source: ec.europa.eu")

p <-
  p +
  scale_fill_manual(values = c("#880044", "#C45E43", "#FFBC42")) +
  theme(
    plot.margin = margin(2.5, 1.5, 1, 1.5, "cm"), 
    text = element_text(family = "Roboto", color = "#D9CAB3"), 
    plot.background = element_rect(fill = "#394032"), 
    plot.title = element_text(size = 18, face = "bold", vjust = 12), 
    plot.subtitle = element_text(size = 11, face = "italic", vjust = 16), 
    plot.caption = element_text(face = "italic")
  )

p +
  inset_element(
    l, 
    left = 0.15,
    right = 1.55,
    bottom = 0.92, 
    top = 1.5,
  )


ggsave(filename = "2022-07-12_TT.png", width = 20, height = 9, unit = "in")
```
