---
title: "Tidy Tuesday - June 27, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
# libraries
library(tidyverse)
library(showtext)
library(tigris)

# fonts
font_add_google("Barlow")
font_add_google("Barlow Condensed")
showtext_auto()

# Read in data
tuesdata <- tidytuesdayR::tt_load(2023, week = 26)
```

```{r Data Exploration}
placeHistory <- tuesdata$us_place_history
placeNames <- tuesdata$us_place_names %>%
  left_join(placeHistory, by = "feature_id") %>%
  filter(!state_name %in% c("American Samoa", "Commonwealth of the Northern Mariana Islands", "Puerto Rico",
                            "United States Virgin Islands", "U.S. Minor Outlying Islands", "Guam", "Alaska", "Hawaii"))

placeNames_city <- placeNames %>%
  mutate(cityTrue = case_when(str_detect(feature_name, "City") == TRUE ~ TRUE, .default = FALSE))

usMap <- map_data("state") %>%
  fortify(region = "region")

placeNames_grouped <- placeNames_city %>%
  filter(cityTrue == TRUE) %>%
  group_by(state_name) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
```

```{r Data Visualization}
plotFinal <- ggplot() +
  geom_point(data = placeNames_city %>% drop_na(prim_long_dec), aes(x = prim_long_dec, y = prim_lat_dec), shape = 20,
             colour = "#AC1D1C", size = 0.1, alpha = 0.2) +
  geom_map(data = usMap, map = usMap, aes(map_id = region, group = group), fill = NA, colour = "#074E67") +
  labs(title = "What's in a Name?",
       subtitle = glue::glue("Geographical distribution of cities across the conterminous United States with 'city' in the name. The top three states with the greatest number of cities with 'city' in the name are {placeNames_grouped[1,1]} with {placeNames_grouped[1,2]}, {placeNames_grouped[2,1]} with {placeNames_grouped[2,2]}, and {placeNames_grouped[3,1]} with {placeNames_grouped[3,2]}."),
       caption = "Source: National Map Staged Products Directory via US Board of Geographic Names | #TidyTuesday | Week 26") +
  theme_void() +
  theme(text = element_text(family = "Barlow Condensed"),
        plot.title = element_text(family = "Barlow", face = "bold", size = 72),
        plot.title.position = "plot",
        plot.subtitle = ggtext::element_textbox_simple(size = 48, lineheight = 0.3),
        plot.caption = element_text(size = 32, hjust = 0.5),
        plot.caption.position = "plot",
        plot.margin = margin(0.5, 1, 0.5, 1, unit = "lines"),
        plot.background = element_rect(colour = "white", fill = "white"),
        panel.background = element_rect(colour = "white", fill = "white"))
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-06-27_HistoricalMarkers/"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), height = 7, width = 11, unit = "in")
```
