---
title: "Tidy Tuesday - April 11, 2023"
output: html_notebook
---

```{r Libraries, Fonts, Data}
library(tidyverse)
library(showtext)
library(lubridate)
library(cowplot)
library(colorspace)

#fonts
font_add_google("Roboto")
font_add_google("Roboto Condensed")
showtext_auto()

#Read in data
tuesdata <- tidytuesdayR::tt_load(2023, week = 15)
```

```{r Data Exploration}
#eggProduction <- tuesdata$`egg-production`
cageFree <- tuesdata$`cage-free-percentages` %>%
  pivot_longer(c(percent_hens, percent_eggs)) %>%
  filter(!is.na(value)) %>%
  mutate(observed_date = as_date(observed_month),
         observed_month = month(observed_date, label = TRUE),
         observed_year = year(observed_date)) %>%
  mutate(name = case_when(name == "percent_eggs"~"Computed percentage of cage-free eggs relative to all table eggs",
                          name == "percent_hens"~"Observed or computed percentage of cage-free hens relative to all table-egg-laying hens")) %>%
  filter(observed_year > 2015)
```

```{r Data Visualization}
plotFinal <- cageFree %>%
  ggplot(aes(observed_date, value, fill = name, color = after_scale(darken(fill, 0.5)))) +
  geom_line(aes(group = name)) +
  geom_point(size = 1.75, shape = 21) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  scale_color_manual(values = c("#990000", "#2986CC")) +
  scale_fill_manual(values = c("#990000", "#2986CC")) +
  labs(x = "",
       y = "",
       title ="Cage-Free Egg Production in the United States",
       subtitle = str_wrap(glue::glue("Cage-free egg production percentages by month between ",
                             "{month(min(cageFree$observed_date), label = TRUE, abbr = FALSE)} ",
                             "{year(min(cageFree$observed_date))} and ",
                             "{month(max(cageFree$observed_date), label = TRUE, abbr = FALSE)} ",
                             "{year(max(cageFree$observed_date))}."), width = 100),
       caption = "Source: The Human League by Samara Mendez | #TidyTuesday") +
  theme_minimal_grid(font_size = 24, font_family = "Roboto") +
  theme(plot.title = element_text(size = 48, face = "bold"),
        plot.title.position = "plot",
        plot.subtitle = element_text(size = 36, family = "Roboto Condensed"),
        legend.position = "top",
        legend.direction = "vertical",
        legend.justification = "left",
        legend.margin = margin(t = -20, b = -10, l = -30),
        legend.title = element_blank(),
        legend.text = element_text(size = 24, family = "Roboto Condensed"),
        legend.key.height = unit(-2, "cm"),
        plot.caption = element_text(size = 20, family = "Roboto Condensed"),
        plot.caption.position = "plot",
        plot.background = element_rect(fill = "#F9F9F9", colour = "#F9F9F9"),
        panel.background = element_rect(fill = "#F9F9F9", colour = "#F9F9F9")) +
  guides(fill = guide_legend(byrow = TRUE))
  
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-04-11_USEggProduction"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.8, dpi = 300,
       height = 8, width = 11, unit = "in")
```
