```{r libraries, data, fonts}
#libraries
library(tidyverse)
library(showtext)
library(tigris)
library(sf)

#data
tuesdata <- tidytuesdayR::tt_load('2022-09-20')

#fonts
font_add_google("Cabin Sketch")
font_add_google("Zilla Slab")
showtext_auto()
```

```{r Data Exploration}
hydroWaste <- tuesdata$HydroWASTE_v10 %>%
  filter(CNTRY_ISO == "USA",
         LEVEL == "Advanced",
         LON_WWTP >= -140,
         LAT_WWTP >= 19,
         !WWTP_NAME == "WOOD TWP STP") %>%
  select(c(LAT_WWTP, LON_WWTP, LAT_OUT, LON_OUT, WWTP_NAME, WASTE_DIS, LEVEL))
```

```{r Spatial Data Conversion}
# US Map
usMap <- states(cb = TRUE) %>%
  filter(!STUSPS %in% c("AK", "HI", "GU", "AS", "MP", "VI", "PR"))

hydroWaste_sf_WWTF <- hydroWaste %>%
  st_as_sf(coords = c("LON_WWTP", "LAT_WWTP"),
           crs = 4326,
           remove = FALSE)
```

```{r Data Visualization}
plotFinal <- ggplot() +
  geom_sf(data = usMap, colour = "#141861", fill = "#141861") +
  geom_sf(data = hydroWaste_sf_WWTF, mapping = aes(colour = log(1+WASTE_DIS)),
          size = 0.25) +
  theme_void() +
  labs(title = "Advanced Wastewater Treatment Plants in the United States",
       subtitle = str_wrap("There are 5,550 wastewater treatment plants located within the continental United States. Of these, five discharge more than one million cubic meters, whereas the average volume discharged from the other 5,545 plants is just over 12,000 cubic meters.", width = 100, ),
       caption = "Macedo et al. 2022 | Inspired by @KittJonathan | TidyTuesday, Week 38")+
  scale_colour_distiller(palette = "Blues") +
  guides(colour = guide_colorbar(title = "Treated Wastewater Discharge (m^3)",
                                 title.position = "top",
                                 direction = "horizontal",
                                 barheight = unit(0.25, "cm"))) +
  theme(text = element_text(family ="Zilla Slab", colour = "#eeeeee"),
        legend.position = "bottom",
        legend.title = element_text(size = 16, hjust = 0.5, vjust = 0.5),
        legend.text = element_text(size = 16),
        plot.title = element_text(family = "Cabin Sketch", size = 42, hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 20, lineheight = 0.5),
        plot.caption = element_text(size = 14),
        plot.caption.position = "plot",
        panel.background = element_rect(fill = "#0f101d", colour = "#0f101d"),
        plot.background = element_rect(fill = "#0f101d", colour = "#0f101d"),
        plot.margin = margin(0.2, 0, 0.2, 0.2, unit = "cm"))
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2022/2022-09-20_WWTP"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.5, dpi = 300,
       height = 8, width = 11, unit = "in")
```
