---
title: "Tidy Tuesday - May 9, 2023"
output: html_notebook
---

```{r Libraries, Fonts, Data}
library(tidyverse)
library(showtext)
library(ggtext)

# Fonts
font_add_google("Roboto")
font_add_google("Roboto Condensed")
showtext_auto()

# Read in Data
tuesdata <- tidytuesdayR::tt_load(2023, week = 19)
```

```{r Data Exploration}
counties <- tuesdata$counties

childcareCosts <- tuesdata$childcare_costs %>%
  left_join(counties, by = "county_fips_code") %>%
  filter(state_name == "California") %>%
  select(c(county_fips_code, study_year, mc_infant:mfcc_preschool, county_name, state_name)) %>%
  pivot_longer(mc_infant:mfcc_preschool, names_to = "median_price_category", values_to = "median_price") %>%
  group_by(study_year, median_price_category) %>%
  reframe(study_year, median_price_category, minVal = min(median_price),
          val = median(median_price), maxVal = max(median_price), n = n()) %>%
  distinct() %>%
  mutate(median_price_category = factor(median_price_category, levels = c("mc_infant", "mc_toddler", "mc_preschool",
                                                                          "mfcc_infant", "mfcc_toddler", "mfcc_preschool"),
                                        labels = c("Infant (CBC)", "Toddler (CBC)", "Preschool (CBC)",
                                                   "Infant (FBC)", "Toddler (FBC)", "Preschool (FBC)")))
```

```{r Data Visualization}
plotFinal <- childcareCosts %>%
  ggplot(aes(study_year, val)) + 
  geom_point(aes(shape = median_price_category, fill = median_price_category, colour = median_price_category), 
             size = 6, position = position_dodge2(width = 0.9)) +
  scale_shape_manual(values = c(20, 21, 22, 23, 24, 25)) +
  scale_fill_manual(values = wesanderson::wes_palette("IsleofDogs1", 6, type = "discrete")) +
  scale_colour_manual(values = wesanderson::wes_palette("IsleofDogs1", 6, type = "discrete")) +

  xlim(c(2007, 2019)) +
  labs(x = "", 
       y = "Median price ($)",
       title = "Childcare Costs in California, 2008-2018",
       subtitle = "This graphic explores the aggregated weekly, full-time median price of center-based (CBC) and family-based (FBC) childcare by age for California from 2008 through 2018. Age categories are defined as 0-23 months, 24-35 months, and 36-54 months in age for infants, toddlers and preschoolers, respectively.",
       caption = "Source: National Database of Childcare Prices | #TidyTuesday | Week 19") +
  cowplot::theme_minimal_grid() +
  theme(text = element_text(size = 28, family = "Roboto Condensed"),
        plot.title.position = "plot",
        plot.title = element_text(size = 48, family = "Roboto", face = "bold"),
        plot.subtitle = element_textbox_simple(size = 30, lineheight = 0.25),
        legend.direction = "horizontal",
        legend.position = "top",
        legend.justification = "center",
        legend.margin = margin(t = 5),
        axis.text = element_text(size = 26),
        plot.caption.position = "plot",
        plot.background = element_rect(color = "#fafafa", fill = "#fafafa"),
        panel.background = element_rect(color = "#fafafa", fill = "#fafafa")) +
  guides(fill = guide_legend(title = "", nrow = 1),
         shape = guide_legend(title = "", nrow = 1),
         colour = guide_legend(title = "", nrow = 1))
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-05-09_ChildcareCosts"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.8, dpi = 300,
       height = 8, width = 11, unit = "in")
```