---
title: "Tidy Tuesday - May 23, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
# Libraries
library(tidyverse)
library(showtext)
library(ggmosaic)
library(patchwork)

# Fonts
font_add_google("Cabin Condensed")
font_add_google("Cabin")
showtext_auto()

# Data
tuesdata <- tidytuesdayR::tt_load(2023, week = 21)
```

```{r data wrangling}
squirrels <- tuesdata$squirrel_data %>%
  mutate(Date = lubridate::mdy(as.character(Date)),
         Day = lubridate::day(Date),
         DayName = weekdays(Date)) %>%
  filter(Age != "?",
         !is.na(Location)) %>%
  mutate(Age = factor(Age, labels = c("Adult", "Juvenile"))) %>%
  mutate(DayName = factor(DayName, levels = c("Monday", "Wednesday",
                                              "Thursday", "Friday", "Saturday", "Sunday")))

squirrelsDays_01 <- squirrels %>%
  group_by(DayName, Age) %>%
  summarise(n = n())

squirrelsDays <- squirrels %>%
  group_by(Day, Age) %>%
  summarise(n = n()) %>%
  mutate(Day = fct_inorder(factor(Day)))
```

```{r data visualization}
plotDays_01 <- squirrelsDays_01 %>%
  ggplot() +
  geom_tile(aes(x = Age, y = DayName, fill = n), height = 0.5) +
  scale_fill_gradientn(colours = c("#92BBBD", "#645197"), breaks = c(100, 200, 300, 400, 500, 600, 700)) +
  labs(x = "",
       y = "") +
  guides(fill = guide_colorbar(title = "Number  of Reportings", title.position = "left", title.hjust = 0.5, 
                               barheight = 1, frame.colour = "grey95")) +
  theme(legend.title = element_text(hjust = 0.5, angle = 90),
        text = element_text(colour = "black"))

plotDays <- squirrelsDays %>%
  ggplot(aes(x = Day, y = n, fill = Age, colour = Age)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#92BBBD", "#645197"), guide = "none") +
  scale_colour_manual(values = c("#92BBBD", "#645197"), guide = "none") +
  labs(x = "Day in Census",
       y = "Number of Reportings") +
  theme(text = element_text(colour = "black"))

plotMosaic <- squirrels %>%
  ggplot() +
  geom_mosaic(aes(x = product(DayName), conds = product(Location), fill = Age, colour = Age)) +
  scale_fill_manual(values = c("#92BBBD", "#645197"), guide = "none") +
  scale_colour_manual(values = c("#92BBBD", "#645197"), guide = "none") +
  scale_x_productlist(labels = c("Above Ground (Adult)", "Above Ground (Juvenile)",
                              "Ground Plane (Adult)", "Ground Plane (Juvenile)")) +
  labs(x = "", 
       y = "") +
  theme(text = element_text(colour = "black"))


Days <- plotMosaic + plotDays_01 +
  plot_layout(widths = c(2, 0.25))

plotFinal <- plotDays / Days +
  plot_annotation(title = "Central Park Squirrel Census (2018)",
                  subtitle = glue::glue("This visualization explores the 2018 Central Park Squirrel Census. Number of squirrels reported by age (",
                                        "<span style='color:#92BBBD'>**Adult**</span> or ",
                                        "<span style='color:#645197'>**Juvenile**</span>) ",
                                        "is visualized in the top panel, while the proportion of reported squirrels that are above the ground (i.e., in a tree) vs. on the ground is explored by age and day of the week. Overall, ",
                                        "<span style='color:#645197'>**Juvenile**</span> ",
                                        "squirrels were reported in lower frequencies than their older counterparts."),
                  caption = "Source: The Squirrel Census | #TidyTuesday | Week 21") &
  theme_minimal() &
  guides(fill = guide_colorbar(title = "Number  of Reportings", title.position = "left", title.hjust = 0.5, 
                               barheight = 8, frame.colour = "grey95")) &
  theme(text = element_text(family = "Cabin Condensed", size = 20, colour = "black"),
        plot.background = element_rect(fill = "grey95", colour = "grey95"),
        panel.background = element_rect(fill = "grey95", colour = "grey95"),
        plot.title = element_text(family = "Cabin", face = "bold", size = 64),
        plot.subtitle = ggtext::element_textbox_simple(size = 32, lineheight = 0.25),
        legend.title = element_text(hjust = 0.5, angle = 90, size = 16),
        legend.text = element_text(size = 16)) 

```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-05-23_Squirrels"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.8, dpi = 300,
              height = 8, width = 11, unit = "in")
```
