---
title: "Tidy Tuesday - May 16, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
# Libraries
library(tidyverse)
library(showtext)
library(geofacet)

# Fonts
font_add_google("Barlow Condensed")
font_add_google("Barlow")
showtext_auto()

# Data
tuesdata <- tidytuesdayR::tt_load(2023, week = 20)
```

```{r data wrangling}
tornados <- tuesdata$tornados %>%
  mutate(decade = (yr - yr %% 10),
         mag = factor(mag),
         group = case_when(is.na(loss)~"No Property Damage", TRUE~"Property Damage"),
         group = factor(group)) %>%
  group_by(st, yr, group) %>%
  summarise(n = n_distinct(om)) %>%
  ungroup() %>%
  group_by(st, yr) %>%
  mutate(perc = n/sum(n))
```

```{r data visualization}
plotFinal <- tornados %>%
  ggplot(aes(x = yr, y = perc, fill = group)) +
  geom_col(width = 1, alpha = 0.85) +
  facet_geo(~st, grid = "us_state_grid2") +
  scale_x_continuous(limits = c(1950, 2022), breaks = seq(1950, 2020, 20)) +
  scale_y_continuous(breaks = seq(0, 1, 0.25), labels = scales::percent) +
  coord_cartesian(expand = FALSE, clip = "off") +
  scale_fill_manual(values = c("#009933", "#FF6347")) +
  labs(x = "",
       y = "",
       title = "Percentage of Tornados with Property Loss by State (1950-2022)",
       subtitle = glue::glue("This graphic explores the proportion of tornadoes that resulted in ",
                             "<span style='color:#FF6347'>**property damage**</span> ",
                             "as compared to those with ",
                             "<span style='color:#009933'>**no property damage**</span> ",
                             "for the United States from 1950 through 2022."),
       caption = "Source: NOAA NWS Storm Prediction Center | #TidyTuesday | Week 20") +
  cowplot::theme_minimal_grid() +
  theme(text = element_text(family = "Barlow Condensed"),
        plot.background = element_rect(fill = "grey95", colour = "grey95"),
        panel.background = element_rect(fill = "grey95", colour = "grey95"),
        plot.title = element_text(family = "Barlow", face = "bold", size = 56,
                                  margin = margin(b = 2, l = 5)),
        plot.title.position = "plot",
        plot.subtitle = ggtext::element_textbox_simple(size = 36, lineheight = 0.25,
                                                       margin = margin(t = 5, b = 5)),
        plot.caption = element_text(size = 28),
        strip.text = element_text(size = 28),
        axis.text = element_text(size = 24),
        axis.text.x = element_text(angle = 45),
        legend.position = "none",
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "lines")
        )
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-05-16_Tornados"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 1, dpi = 300,
       height = 8, width = 11, unit = "in") 
```
