---
title: "Tidy Tuesday - January 24, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
#Libraries
library(tidyverse)
library(showtext)
library(rcartocolor)


#Fonts
font_add_google("Barlow Condensed")
showtext_auto()

#Data
tuesdata <- tidytuesdayR::tt_load(2023, week = 4)
```

```{r}
survivalists <- tuesdata$survivalists
loadouts <- tuesdata$loadouts
episodes <- tuesdata$episodes
seasons <- tuesdata$seasons
```

```{r data wrangling}
survivalLoad <- merge(survivalists, loadouts, by = "name")

freqItemsResult <- survivalLoad %>%
  group_by(item, result) %>%
  summarise(n = n())

freqItems <- survivalLoad %>%
  group_by(item) %>%
  summarise(Popularity = n())

freqItemsStat <- survivalLoad %>%
  group_by(item) %>%
  summarise(Average = mean(result), SD = sd(result))

finalItems <- merge(freqItemsStat, freqItems) %>%
  filter(!is.na(SD),
         Popularity >= 3) 
```  

```{r plotting}
plotFinal <- finalItems %>%
  ggplot(aes(x = reorder(item, Average, decreasing = FALSE), y = Average)) +
  geom_point(aes(size = Popularity, colour = Average), stat = "identity") +
  geom_errorbar(aes(ymin = (Average - SD), ymax = (Average + SD), 
                    color = Average)) +
  geom_text(aes(label = Popularity, size = Popularity), hjust = 0.5, family = "Barlow Condensed", colour = "white", show.legend = FALSE) +
  coord_flip() +
  scale_color_carto_c(palette = "Emrld") +
  labs(x = "",
       y = "Item Performance",
       title = "Alone (TV Series) Loadout Performance",
       subtitle ="Each survivalist enters with 10 items, which items may lead to surviving to episode 10?",
       caption = "Source: {Alone} | Tidy Tuesday ")+
  theme_minimal() +
  theme(text = element_text(family = "Barlow Condensed", colour = "white"),
        panel.background = element_rect(fill = "#BCC6CC", colour = "#BCC6CC"),
        plot.background = element_rect(fill = "#BCC6CC", colour = "#BCC6CC"),
        plot.title = element_text(family = "Barlow Condensed", colour = "#123456", 
                                  size = 64, hjust = 0.5),
        plot.subtitle = element_text(family = "Barlow Condensed", colour = "white",
                                     size = 50, hjust = 0.5),
        axis.text.y = element_text(family = "Barlow Condensed", colour = "white",
                                   size = 38),
        axis.text.x = element_text(family = "Barlow Condensed", colour = "white",
                                   size = 38),
        axis.title.x = element_text(family = "Barlow Condensed", 
                                    colour = "white", size = 38),
        panel.grid.major.y = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(family = "Barlow Condensed", colour = "white",
                                   size = 36),
        legend.title = element_text(family = "Barlow Condensed", colour = "white",
                                   size = 36),
        plot.caption = element_text(family = "Barlow Condensed", colour = "white",
                                   size = 32)) +
  guides(colour = guide_colorbar(title.position = "top", title.hjust = 0.5, 
                                 title.vjust = -1),
         size = guide_legend(title.position = "top", title.hjust = 0.5, 
                             label.position = "bottom"))
```

```{r save final plot}
ggsave("2023-01-24_TT.png", plotFinal, width = 11, height = 8, unit = "in")
```