```{r}
library(tidyverse)
library(PostcodesioR)
library(ggtext)
library(showtext)
library(rnaturalearth)
library(rnaturalearthdata)
library(patchwork)
library(ggdist)
```

```{r}
#Load Fonts
font_add("Roboto", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/Roboto-Regular.ttf", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/Roboto-Bold.ttf")
font_add("Source Sans Pro", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/SourceSansPro-Regular.ttf", "C:/Users/HDailey/AppData/Local/Microsoft/Windows/Fonts/SourceSansPro-Bold.ttf")

#Load Data
tuesdata <- tidytuesdayR::tt_load("2022-06-28")
paygap <- tuesdata$paygap
```

```{r}
#Data Cleaning
paygapClean <- paygap[, c("employer_id",
                          "employer_name",
                          "company_number",
                          "sic_codes",
                          "employer_size",
                          "post_code",
                          "address",
                          "diff_mean_hourly_percent"
  )]

paygapClean <- paygapClean %>%
  mutate(post_code = str_trim(post_code)) %>%
  filter(employer_size != "Not Provided", employer_size == "5000 to 19,999",
         post_code != "NA")

getlatlon <- function(post_code) {
  df <- postcode_lookup(post_code)
  lat <- df$latitude
  lon <- df$longitude
  return(c(lat, lon))
}

lat <- numeric(length = nrow(paygapClean))
lon <- numeric(length = nrow(paygapClean))
for (i in seq_len(nrow(paygapClean))) {
  latlonComb <- getlatlon(paygapClean$post_code[i])
  lat[i] = latlonComb[1]
  lon[i] = latlonComb[2]
}

paygapClean$lat <- lat
paygapClean$lon <- lon

paygapClean <- paygapClean %>%
  filter(lat != "NA")

#General Stats for comparison
totMen <- sum(paygapClean$diff_mean_hourly_percent >0)   #2041, 94%
avgMen <- mean(paygapClean$diff_mean_hourly_percent) #14.6%
maxMen <- slice_max(paygapClean, n = 1, diff_mean_hourly_percent) #Virgin Atlantic, 66.4%

#Plot
UK <- ne_countries(scale = "medium", type = "map_units", returnclass = "sf", country = "United Kingdom")

plotUK <- ggplot() +
  geom_sf(data = UK, fill = "white", colour = "black") + 
  geom_point(data = paygapClean,
            aes(x = lon, y = lat, fill = diff_mean_hourly_percent),
            size = 3,
            pch = 21) +
  theme_void() +
  labs(title = "The United Kingdom's Gender Pay Gap", tag = "With a sample of 2,171 companies having more than \n 5,000 but less than 20,000 employees, approximately \n 94% paid men a greater salary than women. On average,\n  these companies paid men 15% more than women. \n Virgin Atlantic has the greatest pay discrepancy \n with paying men 66% more than women. \n\n Data: gender-pay-gap.service.gov.uk") +
  guides(fill = guide_colorbar(title.position = "top", title.hjust = 1)) +
  scale_fill_gradient2(name = "Mean % Difference in Pay",
                       limits = c(-100, 100), breaks = c(-100, 0, 100)) +
  theme(legend.position = "left",
        #plot.background = element_rect(),
        plot.margin = unit(c(0.5, 5, 0.5, -1), unit = "cm"),
        plot.tag = element_text(size = 20, colour = "black", family = "Roboto"),
        plot.tag.position = c(1.25, 0.5),
        plot.title = element_text(colour = "black", size = 32, hjust = 0, 
                                  vjust = 0, family ="Roboto", face ="bold"),
        legend.text = element_text(size = 16, colour = "black", family="Roboto", face="bold"),
        legend.title = element_text(size = 16, colour = "black", family="Roboto", face="bold"),
        legend.text = element_text(size = 12, colour = "black", family="Roboto", face="bold")
        )
  
ggsave(filename = "2022-06-28_TT.png", plotUK, width = 20, height = 15, unit = "in", bg = "white")
```

```{r}
#Data Cleaning
paygapClean <- paygap[, c("employer_id",
                          "employer_name",
                          "company_number",
                          "sic_codes",
                          "employer_size",
                          "post_code",
                          "address",
                          "diff_mean_hourly_percent"
  )]

paygapClean <- paygapClean %>%
  mutate(post_code = str_trim(post_code),
         size = as.factor(parse_number(employer_size)),
         signPerc = diff_mean_hourly_percent >= 0 ) %>%
  filter(employer_size != "Not Provided", #employer_size == "Less than 250",
         post_code != "NA") %>%
  arrange(abs(diff_mean_hourly_percent))

plotPayGap <- paygapClean %>%
  ggplot(aes(x = size, 
             y = diff_mean_hourly_percent, 
             fill = signPerc)) +
 # geom_boxplot()
  stat_halfeye() +
  ylim(-100, 100) +
  theme_void() +
  labs(title = "Pay Disparities in the UK by Employer Size") +
  theme(panel.background = element_rect(colour = "grey95", fill = "grey95"),
        plot.background = element_rect(color = "grey95", fill = "grey95"),
        plot.margin = unit(c(0.5, 5, 0.5, -1), unit = "cm"),
        plot.title = element_text(colour = "black", size = 32, hjust = 0.5, 
                                  vjust = 0, family ="Source Sans Pro", face ="bold"),
        legend.position = "bottom",
        legend.text = element_text(size = 16, colour = "black", family="Source Sans Pro", face="bold"),
        legend.title = element_text(size = 16, colour = "black", family="Source Sans Pro", face="bold")
        )

ggsave(filename = "2022-06-28_TT-02.png", plotPayGap, width = 20, height = 15, unit = "in", bg = "white")
```

