---
title: "Tidy Tuesday - June 13, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
# libraries
library(tidyverse)
library(showtext)

# fonts
font_add_google("Cabin")
font_add_google("Cabin Condensed")
showtext_auto()

# Read in data
# Woodhouse, Philip; Veldwisch, Gert Jan; Brockington, Daniel; Komakech, Hans C.; Manjichi, Angela; Venot, Jean-Philippe (2018): SAFI Survey Results. doi:10.6084/m9.figshare.6262019.v1
tuesdata <- tidytuesdayR::tt_load(2023, week = 24)
```

```{r Data Exploration}
safiData <- tuesdata$safi_data %>%
  select(c(key_ID, village, affect_conflicts, liv_count, months_lack_food)) %>%
  separate(months_lack_food, c(glue::glue("mo", "{1:11}"))) %>%
  pivot_longer(mo1:mo11) %>%
  na.omit() %>%
  rename("month" = "value") %>%
  select(-name) %>%
  group_by(village) %>%
  count(month) %>%
  ungroup() %>%
  left_join(tuesdata$safi_data %>%
              distinct(key_ID, village, months_lack_food) %>%
              count(village, name = "count"), by = "village") %>%
  mutate(perc = n/count,
         month = factor(month, levels = c("Jan","Feb","Mar","Apr","May","June",
                                          "July","Aug","Sept","Oct","Nov","Dec",
                                          "none")),
         village_label = glue::glue("**{village}** Village (n = {count})")) 

```

```{r Data Visualization}
plotFinal <- safiData %>%
  ggplot(aes(x = perc, y = fct_rev(month))) +
  geom_segment(aes(x = 0, xend = perc, yend = month), colour = "#1CA274") +
  geom_point(colour = "#1CA274") +
  geom_text(aes(label = scales::percent(perc, accuracy = 0.1, drop0trailing = TRUE)),
            hjust = 0, nudge_x = 0.03, size = 12, family = "Cabin Condensed", colour = "#1CA274") +
  scale_x_continuous(limits = c(0,1), expand = c(0,0), label = scales::percent) +
  facet_wrap(~village_label) +
  coord_cartesian(clip = "off") +
  labs(x = "Percentage of Households",
       y = "",
       title = "Percentage of Village Households With Insufficient Food",
       subtitle = "This graphic explores the percentage of village households in Mozambique and Tanzania that have had insufficient food to feed the household by month. This survey data was obtained by SAFI (Studying African Farmer-Led Irrigation) which is a currently running project looking at farming and irrigation methods. This is survey data relating to households and agriculture in Tanzania and Mozambique from November 2016 through June 2017.",
       caption = "Source: SAFI | #TidyTuesday | Week 24\n\nWoodhouse, Philip; Veldwisch, Gert Jan; Brockington, Daniel; Komakech, Hans C.; Manjichi, Angela; Venot, Jean-Philippe (2018): SAFI Survey Results. doi:10.6084/m9.figshare.6262019.v1") +
  cowplot::theme_minimal_vgrid() +
  theme(text = element_text(size = 36, family = "Cabin Condensed"),
        plot.title.position = "plot",
        plot.title = element_text(size = 64, family = "Cabin", face = "bold"),
        plot.subtitle = ggtext::element_textbox_simple(size = 42, lineheight = 0.4, margin = margin(b = 10)),
        plot.margin = margin(0.5, 1, 0.5, 1, unit = "cm"),
        plot.background = element_rect(colour = "grey95", fill = "grey95"),
        panel.spacing = unit(3, "lines"),
        panel.background = element_rect(colour = "grey95", fill = "grey95"),
        strip.background = element_rect(colour = "grey95", fill = "grey95"),
        strip.text = ggtext::element_markdown(size = 40, hjust = 0.5),
        axis.text = element_text(size = 36),
        axis.title.x = element_text(margin = margin(t = 10)),
        plot.caption.position = "plot",
        plot.caption = ggtext::element_textbox_simple(size = 28, hjust = 0, lineheight = 0.2, colour = "grey50"))

```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-06-13_SAFI/"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), height = 8, width = 11, unit = "in")
```
