---
title: "Tidy Tuesday - March 28, 2023"
output: html_notebook
---

```{r Libraries, Fonts, Data}
library(tidyverse)
library(showtext)
library(sf)
library(rnaturalearth)

#fonts
font_add_google("Maven Pro")
showtext_auto()

#Read in data
tuesdata <- tidytuesdayR::tt_load(2023, week = 13)
```

```{r Data Exploration}
transitions <- tuesdata$transitions %>%
  mutate(begin = lubridate::as_datetime(begin),
         end = lubridate::as_datetime(end),
         yrbegin = lubridate::year(begin)) %>%
  filter(yrbegin == 2023)

timeZones <- tuesdata$timezones %>%
  left_join(transitions, by = "zone") %>%
  mutate(dst = as.character(dst)) %>%
  mutate(dst = replace_na(dst, "No"),
         dst = case_when(dst == "TRUE" ~ "Yes", TRUE ~ dst)) %>%
  filter(dst != "FALSE")

world <- ne_countries(returnclass = "sf") %>%
  st_transform(crs = 4326)

worldTZ <- read_sf("ne_10m_time_zones.shp") %>%     # from https://www.naturalearthdata.com/
  st_transform(crs = 4326) %>%
  mutate(zone = as.factor(zone))
```

```{r Data Visualization}
plotFinal <- ggplot() +
  geom_sf(data = world, fill = NA, color = "black", linewidth = 0.15) +
  geom_sf(data = worldTZ, mapping = aes(fill = zone), 
          color = "black", alpha = 0.3, linewidth = 0.1, show.legend = FALSE) +
  ggnewscale::new_scale("fill") +
  geom_text(data = tibble(x = seq(-165, 165, 15), y = -87, 
                          label = c(as.character(glue::glue("{seq(-11, 0, 1)}")),
                                    as.character(glue::glue("+{seq(1, 11, 1)}")))),
            aes(x = x, y = y, label = label), fontface = "bold", size = 6) +
  geom_point(data = timeZones, mapping = aes(x = longitude, y = latitude, fill = fct_rev(dst)), 
             pch = 21, size = 1,
             alpha = 0.7) +
  scale_fill_manual(name = "Observes Daylight Savings?", values = c( "#01996F", "#FF930A")) +
  coord_sf(expand = FALSE, clip = "off") +
  labs(title = "Time Zone Map with Daylight Savings Time Locations",
       subtitle = "Global locations of times zones where day light savings is observed as of 2023.",
       caption = "Source: IANA tz database, {rnaturalearth} package | TidyTuesday") +
  theme_void(base_family = "Maven Pro") +
  guides(fill = guide_legend()) +
  theme(plot.title = element_text(face = "bold", size = 44, hjust = 0.5,
                                  margin = margin(t = -1, unit = "lines")),
        plot.subtitle = element_text(size = 30),
        legend.position = "top",
        legend.justification = "left",
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20),
        plot.caption = element_text(size = 16),
        panel.background = element_rect(fill = "#C1E8E2", colour = "#C1E8E2"),
        plot.background = element_rect(fill = "#C1E8E2", colour = "#C1E8E2"),
        plot.margin = margin(-3, 1, -5, 1, unit = "lines"))

```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-03-28_TimeZones"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.5, dpi = 300,
       height = 8, width = 11, unit = "in")
```
