---
title: "Tidy Tuesday - February 21, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
library(tidyverse)
library(showtext)
library(ggsankey)

#fonts
font_add_google("Zilla Slab")
font_add_google("Georama")
showtext_auto()

#Read in data
tuesdata <- tidytuesdayR::tt_load(2023, week = 8)
```

```{r Data Exploration}
# Initial Data Exploration
bobRoss <- tuesdata$bob_ross %>%
  select(-c(painting_index, img_src, painting_title, episode,
            youtube_src, colors, color_hex)) %>%
  group_by(season) %>%
  summarise(across(Black_Gesso:Alizarin_Crimson, ~sum(.x, na.rm = TRUE))) %>%
  pivot_longer(cols = -season,
               names_to = "colors",
               values_to = "n") %>%
  mutate(colors = str_replace_all(colors, "_", " "))

# Create Color Look Up Table
bobRoss_Colors <- tuesdata$bob_ross %>%
  select(colors, color_hex) %>%
  unique() %>%
  mutate(colors = gsub("\\[|\\]", "", colors),
         colors = gsub("\\'|\\'", "", colors),
         colors = gsub("\\\\r", "", colors),
         colors = gsub ("\\\\n", "", colors),
         colors = str_split(colors, ",")) %>%
  mutate(color_hex = gsub("\\[|\\]", "", color_hex),
         color_hex = gsub("\\'|\\'", "", color_hex),
         color_hex = str_split(color_hex, ",")) %>%
  unnest(c(colors, color_hex)) %>%
  mutate(color_hex = str_trim(color_hex),
         colors = str_trim(colors)) %>%
  unique()

# Join Season Data Frame and Look Up Table
bobRoss <- bobRoss %>%
  left_join(bobRoss_Colors, by = "colors", multiple = "all")
```

```{r Data Visualization}
plotFinal <- bobRoss %>%
  ggplot(aes(x = season, value = n, node = colors, fill = I(color_hex))) + 
  geom_sankey_bump(space = 4,
                   color = "transparent",
                   smooth = 5,
                   alpha = 0.8) +
  labs(title = "Bob Ross Paintings",
       subtitle = expression(paste("Average number of times a color from the paintings of Bob Ross featured in the TV Show, ", italic("The Joy of Painting"), ", was used per season")),
       caption = "Source: Bob Ross Colors Data Package | TidyTuesday | Inspired by nrennie") +
  theme_void() +
  theme(text = element_text(family = "Georama"),
        plot.margin = margin(0, 0.1, 0, 0.1),
        plot.title = element_text(family = "Zilla Slab",
                                  color = "#F0F5F5", face = "bold", size = 84, hjust = 0.5),
        plot.subtitle = element_text(color = "#F0F5F5", size = 36, hjust = 0.5),
        plot.caption = element_text(color = "#F0F5F5", size = 32, hjust = 1),
        plot.background = element_rect(fill = colorspace::lighten("#4F6A7B", amount = 0.3),
                                       color = colorspace::lighten("#4F6A7B", amount = 0.3)),
        panel.background = element_rect(fill = colorspace::lighten("#4F6A7B", amount = 0.3),
                                        color = colorspace::lighten("#4F6A7B", amount = 0.3))
  )
  

```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-02-21_BobRoss"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), height = 8, width = 11, unit = "in")
```