---
title: "Tidy Tuesday - June 6, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
# Libraries
library(tidyverse)
library(showtext)
library(gtable)
library(grid)

# Fonts
font_add_google("Cabin Condensed")
font_add_google("Cabin")
showtext_auto()

# Data - read in manually
# tuesdata <- tidytuesdayR::tt_load("2023-06-06")
owidEnergy <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-06/owid-energy.csv')
```

```{r Data Wrangling}
owidEnergy_filtered <- owidEnergy %>%
  filter(country %in% c("Africa", "Asia", "Middle East (BP)", "Europe", "Oceania",
         "North America", "South America", "World"),
         year == 2021) %>%
  mutate(country = case_when(country == "Middle East (BP)"~"Middle East",
                             .default = country)) %>%
  select(ends_with(c("country", "electricity"))) %>%
  select(starts_with(c("country", "fossil", "nuclear", "renewables", "coal", "gas"))) %>%
  pivot_longer(cols = -country,
               names_to = "energy_type",
               values_to = "energy_val") %>%
  mutate(energy_val = prop.table(energy_val), .by = country,
         energy_type = case_when(energy_type == "fossil_electricity"~"Fossil",
                                 energy_type == "nuclear_electricity"~"Nuclear",
                                 energy_type == "renewables_electricity"~"Renewables",
                                 energy_type == "coal_electricity"~"Coal",
                                 energy_type == "gas_electricity"~"Gas",
                                 .default = energy_type))

```

```{r Data Visualization}
plotFinal <- owidEnergy_filtered %>%
  ggplot(aes(energy_type, energy_val)) +
  geom_polygon(aes(group = country), fill = "#FF5800", colour = "#FF5800") +
  scale_x_discrete(limits = c("Fossil", "Gas", "Renewables", "Coal", "Nuclear"),
                   labels = c("Fossil", "Gas", "Renewables", "Coal", "Nuclear")) +
  labs(x = "",
       y = "",
       title = "Global Energy Generation",
       subtitle = "This graphic explores the proportion of different energy sources (fossil, nuclear, renewable, coal and gas) in total electricity generation for the seven major continents in 2021. Continents in the global north generally had more diverse electrical generation portfolios, whereas continents in the global south generally had less diverse electrical generation portfolios. World electrical energy generation still comes mostly from fossil fuels and coal with lower proportions resulting from renewable energy sources.",
       caption = "Source: OWID | #TidyTuesday | Week 23") +
  ggmulti::coord_radial() +
  facet_wrap(vars(country), nrow = 2) +
  theme_minimal() +
  theme(text = element_text(family = "Cabin Condensed", colour = "grey95"),
        plot.title = ggtext::element_textbox(family = "Cabin", face = "bold", size = 48,
                                             margin = margin(t = 3, b = 1)),
        plot.title.position = "plot",
        plot.subtitle = ggtext::element_textbox_simple(size = 28, lineheight = 0.3,
                                                       margin = margin(t = 5, b = 5)),
        panel.spacing = unit(5, "lines"),
        axis.text = element_text(colour = "grey95"),
        strip.text = element_text(colour = "grey95", face = "bold", size = 20),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 22, colour = "#FF5800", face = "bold", vjust = 0),
        plot.margin = margin(l = 35, r = 35),
        plot.caption.position = "plot",
        plot.caption = element_text(size = 24, hjust = 1),
        plot.background = element_rect(fill = colorspace::lighten("grey5", amount = 0.3), 
                                       colour = colorspace::lighten("grey5", amount = 0.3)),
        panel.background = element_rect(fill = colorspace::lighten("grey5", amount = 0.3), 
                                        colour = colorspace::lighten("grey5", amount = 0.3))
        )
```


```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-06-06_Energy"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.8, dpi = 300,
              height = 6, width = 11, unit = "in")
```