---
title: "Tidy Tuesday - March 21, 2023"
output: html_notebook
---

```{r Libraries, Fonts, Data}
library(tidyverse)
library(showtext)
library(ggtext)

#fonts
font_add_google("VT323")
font_add_google("Share Tech")
showtext_auto()

#Read in data
tuesdata <- tidytuesdayR::tt_load(2023, week = 12)
```

```{r Data Exploration}
programLang <- tuesdata$languages %>%
  filter(line_comment_token %in% c("#", "//", ";", "%")) %>%
  group_by(line_comment_token) %>%
  slice_head(n = 10) %>%
  mutate(n = factor(row_number(), levels = 1:10)) %>%
  ungroup() %>%
  select(line_comment_token, n, title, appeared, last_activity, language_rank) %>%
  pivot_longer(cols = c(appeared, last_activity),
               names_to = "type",
               values_to = "year") %>%
  mutate(title = paste0(title, "\nRank: ", language_rank))
```

```{r Data Visualization}
plotFinal <- ggplot(programLang) +
  geom_text(aes(x = 1950, y = n, label = title), family = "VT323", colour = "#00ff00", size = 8, 
            lineheight = 0.25, vjust = 0.5) +
  geom_line(aes(x = year, y = n, group = n), colour = "#00ff00", linetype = "dashed") +
  geom_point(aes(x = year, y = n), colour = "#00ff00", pch = 15) +
  
  facet_wrap(~line_comment_token, nrow = 1,
             labeller = labeller(line_comment_token = c("#" = "Comment Token: #",
                                                        "%" = "Comment Token: %",
                                                        "//" = "Comment Token: //",
                                                        ";" = "Comment Token: ;"))) +
  scale_y_discrete(limits = rev) +
  scale_x_continuous(breaks = c(1960, 1980, 2000, 2020),
                     limits = c(1930, 2030),
                     expand = c(0,0)) +
  labs(x = "", 
       y = "",
       title = "Programming Languages",
       subtitle = str_wrap("Using the Programming Languages DataBase, there are over 3,300 programming languages listed. In examining comment tokens, 205 use <span style='font-size:34.0px;font-weight:bold;'>// </span>, 101 use <span style='font-size:34.0px;font-weight:bold;'># </span>, 64 use <span style='font-size:34.0px;font-weight:bold;'>; </span>, 15 use <span style='font-size:34.0px;font-weight:bold;'>%</span> and approximately 3,280 do not have a comment token listed."),
       caption = "Source: Programming Languages DataBase | TidyTuesday") +
  theme_void() +
  theme(plot.background = element_rect(fill = colorspace::lighten("#1C1C1C", amount = 0.1), 
                                       colour = colorspace::lighten("#1C1C1C", amount = 0.1)),
        panel.background = element_rect(fill = colorspace::lighten("#1C1C1C", amount = 0.1),
                                        colour = "#00ff00"),
        plot.title = element_text(family = "VT323", colour = "#00ff00", face = "bold", size = 65,
                                  margin = margin(0.1, 0.25, 0.1, 0.25, unit = "lines"),
                                  hjust = 0.5),
        plot.subtitle = element_textbox_simple(family = "Share Tech", colour = "#00ff00", size = 24,
                                               lineheight = 0.5,
                                               margin = margin(0.5, 0.25, 0.1, 0.25, unit = "lines")),
        plot.caption = element_text(family = "Share Tech", colour = "#00ff00", size = 16,
                                    margin = margin(0.1, 0.25, 0.1, 0, unit = "lines")),
        strip.text = element_text(family = "VT323", colour = "#00ff00", size = 24,
                                  margin = margin(0, 0, 0.1, 0, unit = "lines")),
        axis.line.x = element_line(colour = "#00ff00"),
        axis.text.x = element_text(family = "Share Tech", colour = "#00ff00", size = 20,
                                   margin = margin(0.1, 0, 0.1, 0, unit = "lines")),
        plot.margin = margin(0, 1, 0, 1, unit = "lines"))
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-03-21_ProgrammingLanguages"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.6, dpi = 300,
       height = 8, width = 11, unit = "in")
```
