---
title: "Tidy Tuesday - May 30, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
# Libraries
library(tidyverse)
library(showtext)
library(ggdist)
library(ggrepel)

# Fonts
font_add_google("Cabin Condensed")
font_add_google("Cabin")
showtext_auto()

# Data
tuesdata <- tidytuesdayR::tt_load(2023, week = 22)
```

```{r Data Wrangling}
oldestPeople <- tuesdata$centenarians %>%
  mutate(gender = str_to_title(gender),
         still_alive = str_to_title(still_alive),
         label = glue::glue("{rank}: {name}\n({place_of_death_or_residence})"))
```

```{r Data Visualization}
plotFinal <- oldestPeople %>%
  ggplot(aes(x = age, y = gender)) +
  geom_dots(aes(colour = still_alive, fill = after_scale(colorspace::lighten(colour, 0.5)),
                group = NA)) +
  geom_label_repel(data = oldestPeople %>%
              filter(rank <= 5), aes(label = label, segment.size = 0.3), nudge_y = 0.5, 
              family = "Cabin Condensed", colour = "#3D3939", lineheight = 0.25, size = 8, alpha = 0.8) +
  scale_x_continuous(breaks = seq(111, 123, 2)) +
  scale_y_discrete(expand = c(0.1, 0.1)) +
  scale_colour_manual(values = c("#F8A62D", "#3D3939")) +
  labs(x = "Age",
       y = "Gender",
       title = "Oldest People as of May 25, 2023 (Verified)",
       subtitle = "This visualization explores the verified and known 100 oldest people by the date of their death, or on the date the dataset was extracted. Included are the rank and names of the five oldest individuals by age and gender.",
       caption = "Source: Wikipedia via @frankiethull | #TidyTuesday | Week 22") +
  cowplot::theme_minimal_grid() +
  theme(text = element_text(family = "Cabin Condensed", size = 32),
        plot.title = element_text(family = "Cabin", face = "bold", size = 64),
        plot.title.position = "plot",
        plot.subtitle = ggtext::element_textbox_simple(lineheight = 0.25, size = 40),
        legend.position = "top",
        legend.justification = "left",
        legend.direction = "horizontal",
        legend.margin = margin(l = -3, unit = "lines"),
        axis.text = element_text(size = 28),
        plot.caption.position = "plot",
        plot.caption = element_text(size = 28),
        plot.background = element_rect(fill = "grey95", colour = "grey95"),
        panel.background = element_rect(fill = "grey95", colour = "grey95")) +
  guides(colour = guide_legend(title = "Status at time when article was referenced: "))
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-05-30_OldestPeople"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.8, dpi = 300,
              height = 8, width = 11, unit = "in")
```
