---
title: "Tidy Tuesday - March 14, 2023"
output: html_notebook
---

```{r Libraries, Fonts, Data}
library(tidyverse)
library(showtext)
library(geomtextpath)
library(ggtext)
library(ggforce)

#fonts
font_add_google("Archivo")
showtext_auto()
#Read in data
tuesdata <- tidytuesdayR::tt_load(2023, week = 11)
```

```{r Data Exploration}
drugsEU <- tuesdata$drugs %>%
  select(category, authorisation_status, condition_indication) %>%
  filter(category == "veterinary") %>%
  drop_na() %>%
  mutate(status = case_when(authorisation_status == "authorised" ~ "Authorised",
                            authorisation_status != "authorised" ~ "Refused/Withdrawn")) %>%
  mutate(condition_indication = tolower(condition_indication)) %>%
  mutate(`Flea and Tick` = str_detect(condition_indication, "fleas|flea|ticks|tick"),
         `Anxiety` = str_detect(condition_indication, "anxiety"),
         `Heartworm` = str_detect(condition_indication, "heartworm"),
         `Pain` = str_detect(condition_indication, "pain")) %>%
  select(-c(condition_indication, authorisation_status, category)) %>%
  pivot_longer(-status, values_to = "is_drug", names_to = "condition") %>%
  group_by(status, condition) %>%
  summarise(total = sum(is_drug)) %>%
  ungroup() %>%
  group_by(condition) %>%
  mutate(all_condition = sum(total)) %>%
  mutate(proportion = total/all_condition) %>%
  select(-c(total, all_condition))
```

```{r Data Visualization}
plotFinal <- ggplot(drugsEU) +
  facet_wrap(~condition, nrow = 2, ncol = 2) +
  geom_shape(data = data.frame(x = c(-0.02, 2.02, 2.02, -0.02, -0.02),
                               y = c(-0.02, -0.02, 1.02, 1.02, -0.02)),
             mapping = aes(x = x, y = y),
             fill = "tomato",
             radius = unit(0.7, 'cm')) +
  geom_shape(data = data.frame(x = c(-0.02, 2.02, 2.02, -0.02, -0.02),
                               y = c(-0.02, -0.02, 1.02, 1.02, -0.02),
                               condition = "Anxiety"),
             mapping = aes(x = x, y = y),
             fill = "seagreen",
             radius = unit(0.7, 'cm')) +
  geom_shape(data = data.frame(x = c(-0.02, 1.02, 1.02, -0.02, -0.02),
                               y = c(-0.02, -0.02, 1.02, 1.02, -0.02)),
             mapping = aes(x = x, y = y),
             fill = "seagreen",
             radius = unit(0.7, 'cm')) +
  geom_rect(data = filter(drugsEU, status == "Authorised", condition != "Anxiety"),
               mapping = aes(xmin = 0.5,
                             xmax = proportion*2,
                             ymin = -0.02,
                             ymax = 1.02),
               fill = "seagreen") +
  geom_text(data = filter(drugsEU, status == "Authorised"),
            mapping = aes(x = 0.2,
                          y = 0.5,
                          label = condition),
            colour = "gray97",
            hjust = 0,
            size = 9,
            fontface = "bold",
            family = "Archivo") +
  labs(x = "",
       y = "") +
  ggtitle("Veterinary Drug Authorisation by the European Medicines Agency",
       subtitle = str_wrap("The European Medicines Agency (EMA) regulates and directs drug development
                          in humans and animals, as well as decides on whether to \n\nauthorise marketing 
                          materials for new drugs in Europe. Here, we explore veterinary drug  
                          authorisation by the EMA four common conditions experienced by domesticated
                          animals and the percentage of drugs where were <span style='color:seagreen'> authorised </span> or <span style='color:tomato'> refused/withdrawn </span>.")) +
  theme_void() +
  theme(strip.text = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        legend.position = "none",
        plot.title = element_markdown(colour = "black", family = "Archivo", size = 30, hjust = 0.5,
                                      margin = margin(t = 0.2, b = 0.2, unit = "cm")),
        plot.subtitle = element_textbox_simple(lineheight = 0.5, colour = "black", family = "Archivo", size = 20,
                                               hjust = 0.5, margin = margin(0.2, 0.2, 0, 0.2, unit = "cm")),
        plot.background = element_rect(fill = "gray97", colour = "gray97"),
        panel.background = element_rect(fill = "gray97", colour = "gray97"))
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-03-14_EUDrugDevelopment"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.5, dpi = 300,
       height = 8, width = 11, unit = "in")
```   
