---
title: "Tidy Tuesday - May 2, 2023"
output: html_notebook
---

```{r Libraries, Fonts, Data}
library(tidyverse)
library(showtext)
library(ggtext)

# Fonts
font_add_google("Roboto")
font_add_google("Roboto Condensed")
showtext_auto()

# Read in Data
tuesdata <- tidytuesdayR::tt_load(2023, week = 18)
```

```{r Data Exploration}
plots <- tuesdata$plots
species <- tuesdata$species
surveys <- tuesdata$surveys  %>%
  left_join(plots, by = "plot") %>%
  left_join(species, by = "species") %>%
  select(c(censusdate:year, treatment.x, scientificname:commonname))
  
speciesSelected <- surveys %>%
  count(commonname, scientificname, sort = TRUE) %>%
  slice_head(n = 3) %>%
  mutate(commonname_title = str_to_title(commonname)) %>%
  mutate(name = glue::glue("**{commonname_title}**<br>(n = {n})"))

surveyFiltered <- surveys %>%
  filter(commonname %in% speciesSelected$commonname) %>%
  left_join(speciesSelected, by = "commonname") %>%
  count(name, year, treatment.x) %>%
  mutate(treatment.x = str_to_title(treatment.x))
```

```{r Data Visualization}
plotFinal <- ggplot(surveyFiltered, aes(x = year, y = n, colour = treatment.x)) +
  geom_line(key_glyph = draw_key_rect, linewidth = 0.8) +
  scale_x_continuous(limits = c(1978, 2022)) +
  MetBrewer::scale_colour_met_d(name = "Ingres") +
  facet_wrap(~name, scales = "free_x", nrow = 3, ncol = 1) +
  labs(x = "",
       y = "Number of Records",
       colour = "Treatment Type:",
       title = "Portal Project: Desert Rodents",
       subtitle = "The Portal Project is a long-term ecological study being conducted near Portal, AZ. Since 1977, the site has been used to study the interactions among rodents, ants and plants and their respective responses to climate. This graphic shows the number of records for 3 rodent species by treatment type from 1978 to 2022.",
       caption = "Source: Portal Project | #TidyTuesday | Week 18") +
  cowplot::theme_minimal_grid() +
  theme(text = element_text(family = "Roboto Condensed"),
        plot.background = element_rect(fill = "grey95",
                                       colour = "grey95"),
        panel.background = element_rect(fill = "grey95",
                                       colour = "grey95"),
        plot.title.position = "plot",
        plot.title = element_text(family = "Roboto", face = "bold", size = 48),
        plot.subtitle = element_textbox_simple(size = 26, lineheight = 0.25, margin = margin(b = 5)),
        legend.position = "top",
        legend.justification = "center",
        legend.text = element_text(size = 24),
        legend.title = element_text(size = 24),
        legend.box.margin = margin(t = 2, b = -5),
        strip.text = element_textbox_simple(size = 24, lineheight = 0.5),
        axis.text = element_text(size = 26),
        axis.title.y = element_text(size = 24),
        plot.caption.position = "plot",
        plot.caption = element_text(size = 18))
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-05-02_PortalProject"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), scale = 0.8, dpi = 300,
       height = 8, width = 11, unit = "in")
```