---
title: "Tidy Tuesday - June 22, 2023"
output: html_notebook
---
```{r Libraries, Fonts, Data}
# libraries
library(tidyverse)
library(showtext)

# fonts
font_add_google("VT323")
font_add_google("Share Tech")
showtext_auto()

# Read in data
tuesdata <- tidytuesdayR::tt_load(2023, week = 25)
```

```{r Data Exploration}
places <- tuesdata$places
ufo <- tuesdata$ufo_sightings

countUFO <- ufo %>%
  filter(reported_date_time > "2000-01-01") %>%
  filter(country_code == "US") %>%
  group_by(country_code, state, city) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  inner_join(places, by = c("country_code" = "country_code",
                            "state" = "state",
                            "city" = "city"), 
             multiple = "all") %>%
  select(-c(alternate_city_names, timezone, elevation_m)) %>%
  filter(population >= 50000) %>%
  mutate(sightingRate = count / population) %>%
  arrange(desc(sightingRate)) %>%
  mutate(rank = row_number()) %>%
  filter(rank <= 100)

mapData <- map_data("state")
```

```{r Data Visualization}
plotFinal <- ggplot() +
  geom_path(data = mapData, aes(x = long, y = lat, group = group), colour = "#00ff00") +
  geom_point(data = countUFO, aes(x = longitude, y = latitude, size = sightingRate),
             show.legend = FALSE,
             colour = case_when(countUFO$rank <= 20 ~ "#FF033E", .default = "#8A2BE2"),
             alpha = 0.7) +
  ggrepel::geom_label_repel(data = countUFO, aes(x = longitude, y = latitude,
                                                 label = case_when(rank <= 20 ~ city, .default = "")),
                            fill = colorspace::lighten("#1C1C1C", amount = 0.1),
                            colour = "#00FF00",
                            force = 50, 
                            family = "VT323",
                            fontface = "bold",
                            seed = 2023,
                            size = 10) +
  labs(title = "UFO Sightings in the United States",
       subtitle = glue::glue("This visualization explores the UFO sightings in the United States for cities with a minimum population greater than 50,000. ",
                             "<span style='color:#8A2BE2'>**Top 100 cities**</span>",
                             " with the most reported UFO sighting per person since January 2000. ",
                             "<span style='color:#FF033E'>**Top 20 cities**</span>",
                             " are labeled. **Size corresponds to number of signtings**"),
       caption = "Source: National UFO Reporting Center | #TidyTuesday | Week 25") +
  cowplot::theme_map() +
  theme(text = element_text(family = "VT323", colour = "#00ff00", size = 32),
        plot.title = element_text(face = "bold", size = 72),
        plot.subtitle = ggtext::element_textbox_simple(family = "Share Tech", size = 40, lineheight = 0.3, 
                                                       margin = margin(b = 1, unit = "lines")),
        plot.caption = element_text(hjust = 0.5, margin = margin(t = -1, unit = "lines")),
        plot.background = element_rect(fill = colorspace::lighten("#1C1C1C", amount = 0.1), 
                                       colour = colorspace::lighten("#1C1C1C", amount = 0.1)),
        panel.background = element_rect(fill = colorspace::lighten("#1C1C1C", amount = 0.1),
                                        colour = colorspace::lighten("#1C1C1C", amount = 0.1)))
```

```{r Save}
ggsave(plot = plotFinal, path = here::here("2023/2023-06-20_UFO/"),
       paste0(format(Sys.Date(), "%Y-%m-%d"), "_TT", ".png"), height = 6, width = 11, unit = "in")
```
