```{r library data and fonts}
#libraries
library(tidyverse)
library(showtext)
library(lubridate)
library(ggrepel)
library(ggtext)
library(ggthemes)

#data
#tuesdata <- tidytuesdayR::tt_load('2022-08-23')
#chips <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-08-23/chips.csv')
chips <- read.csv("chip_dataset.csv")


#fonts
font_add_google("Roboto")
showtext_auto()
```

```{r data analysis}
chips <- chips %>%
  janitor::clean_names()

chipConsoles <- chips %>%
  mutate(console = case_when(str_detect(product, "Playstation") ~ "Playstation",
                             str_detect(product, "Xbox") ~ "Xbox",
                             str_detect(product, "Wii") ~ "Wii"),
         model = case_when(str_detect(product, "Playstation 2") ~ "Playstation 2",
                           str_detect(product, "Playstation 3") ~ "Playstation 3",
                           str_detect(product, "Playstation 4") ~ "Playstation 4",
                           str_detect(product, "Playstation 5") ~ "Playstation 5",
                           str_detect(product, "Portable") ~ "Portable",
                           str_detect(product, "Vita") ~ "Portable",
                           str_detect(product, "Xbox 360") ~ "Xbox 360",
                           str_detect(product, "Xbox One") ~ "Xbox One",
                           str_detect(product, "Xbox Series X") ~ "Xbox Series X",
                           str_detect(product, "Xbox Series S") ~ "Xbox Series S",
                           str_detect(product, "Wii") ~ "Wii",
                           str_detect(product, "Wii U") ~ "Wii U")) %>%
  filter(!is.na(console)) %>%
  filter(release_date != "NaT") %>%
  mutate(release_date = as.Date(release_date)) %>%
  mutate(label = str_remove(product, "GPU.*"),
         label = paste0(label, "\n", process_size_nm, "nm"),
         label = str_replace(label, "Playstation", "PlayStation"),
         col = if_else(console == "Xbox", "#367C21", 
                       if_else(console == "Playstation", "#1D3E87", "lightblue")))

plotConsole <- ggplot(chipConsoles) +
  geom_point(aes(x = release_date, y = tdp_w/die_size_mm_2, color = col, size = process_size_nm), shape = 15) +
  geom_line(aes(x = release_date, y = tdp_w/die_size_mm_2, group = interaction(console, model), color = col), size = 0.25) +
  geom_text_repel(aes(x = release_date, y = tdp_w/die_size_mm_2, label = label, color = colorspace::lighten(col, 0.2)), 
                  size = 4, family = "Roboto", bg.color = "white", seed = 11, lineheight = 0.9) +
  geom_richtext(data = NULL, aes(x = as.Date("2021-01-01"), y = 1.15, label = "**<span style='color:#1D3E87;'>PlayStation</span>**, **<span style='color:#367C21;'>Xbox</span>** and **<span style='color:lightblue;'>Wii</span>** <br> GPU efficiency<br><span style = 'font-size:18pt'>(watts per mm²)</span><br><span style = 'font-size:12pt; color:gray40'>Source: The CHIP Dataset</span>"), family = "Roboto", size = 10, vjust = 1, hjust = 1, fill = NA, label.color = NA) +
  scale_size_area(max_size = 6) +
  scale_x_date(date_labels = "%Y", minor_breaks = "1 year") +
  scale_color_identity() +
  coord_cartesian(clip = "off") +
  theme_solarized(base_family = "Roboto") +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "#fdf6e3", color = NA),
    axis.title = element_blank(),
    plot.margin = margin(10, 5, 5, 5),
    axis.text.x = element_text(family = "Roboto", size = 12),
    axis.text.y = element_text(family = "Roboto", size = 12)
  )

ggsave("2022-08-23_TT.png", width = 5, height = 5, unit = "in")

```